format: yamanifest
version: 1.0
---
work/access-om3-MOM6-CICE6-WW3:
  fullpath: /g/data/vk83/prerelease/apps/spack/0.22/release/linux-rocky8-x86_64_v4/oneapi-2025.2.0/access3-2025.08.000-xlfncusveydkbdloex7dpbu3qyeaqdcp/bin/access-om3-MOM6-CICE6-WW3
  hashes:
    binhash: 73e29ca1a43a85bd52ef131b27b6e1a4
    md5: 54264b892f5e7670ae6e13cb048855e2
